service: phonebook-frontend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    NUXT_API_BASE_URL: ${env:NUXT_API_BASE_URL, 'http://localhost:5500'}
    NUXT_SESSION_PASSWORD: ${env:NUXT_SESSION_PASSWORD, 'change-me-to-a-secure-password'}

functions:
  nuxt:
    handler: .output/server/index.handler
    memorySize: 512
    timeout: 15
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
